language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
