language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --no-interaction

script:
    - composer test-unit
after_success:
    - bash <(curl -s https://codecov.io/bash)
